---
# Ansbile playbook to combine verifing services in two differnt family of servers checking different services
# roles are defined for each play. For the below play, ansible will execute the yaml file located at roles\nginx\tasks\main.yml
# If defining varibles for the roles, it's defined as the same name as that of the hosts defined here
- name: Check if ngnix service is running on ngnix boxes
  hosts: nginx_servers
  roles:
    - nginx

- name: Check if NolioASAP and nolioagent is running on nolio boxes
  hosts: nolio_servers
  gather_facts: no
  roles:
    - nolio